server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://112.124.46.10:3306/faceg
    username: root
    password: root
  application:
    name: service_provider   #微服务名称
mybatis:
  type-aliases-package: com.yang.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/  #注册地址