server:
  port: 10010
spring:
  application:
    name: yang-zuul
zuul:
  routes:
    service-provider: /provider/**
  prefix: /api
#      path: /service-provider/**
#      serviceId: service-provider
      # url: http://localhost:8081
eureka:
  client:
    registry-fetch-interval-seconds: 5 # \u83B7\u53D6\u670D\u52A1\u5217\u8868\u7684\u5468\u671F\uFF1A5s
    service-url:
      defaultZone: http://localhost:10086/eureka/
